spring:
  application:
    name: book-management
    datasource:
      url: jdbc:mysql://localhost:3306/book_management
      username: your_username
      password: your_password
      driver-class-name: com.mysql.cj.jdbc.Driver

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080